return {
--   {
--     "mfussenegger/nvim-dap",
--     dependencies = {
--       "rcarriga/nvim-dap-ui",
--     },
--     config = function()
--       local dap, dapui = require("dap"), require("dapui")
--       dap.listeners.before.attach.dapui_config = function()
--         dapui.open()
--       end
--       dap.listeners.before.launch.dapui_config = function()
--         dapui.open()
--       end
--       dap.listeners.before.event_terminated.dapui_config = function()
--         dapui.close()
--       end
--       dap.listeners.before.event_exited.dapui_config = function()
--         dapui.close()
--       end
--       local setKey = vim.keymap.set
--       setKey("n", [[<Leader>dt]], dapui.toggle)
--       setKey("n", [[<Leader>db]], dap.toggle_breakpoint)
--       setKey("n", [[<Leader>dc]], dap.continue)
--     end,
--   },
--   {
--     "rcarriga/nvim-dap-ui",
--     dependencies = {
--       "mfussenegger/nvim-dap",
--       "nvim-neotest/nvim-nio",
--     },
--     config = function()
--       require("dapui").setup()
--     end,
--   },
--   {
--     "mfussenegger/nvim-dap-python",
--     ft = "python",
--     dependencies = {
--       "mfussenegger/nvim-dap",
--       "rcarriga/nvim-dap-ui",
--     },
--     config = function(_, opts)
--       local path = "C:\\Users\\xuehu\\AppData\\Local\\nvim-data\\mason\\packages\\debugpy\\venv\\Scripts\\python"
--       require("dap-python").setup(path)
--     end,
--   },
}
